### ISSUE TITLE
Maximum call stack size exceeded after passing data to `new Table` after it is returned from `parseRecordBatch`

### ISSUE THREAD

**Issue by vildantursicsymphony** [kylebarron/arrow-js-ffi#51] opened 2023-10-12 21:36 UTC
Hi,
I've been trying to setup small example of getting data from parquet to json.
So far everything works except when I try to get data from `parseRecordBatch`, after I generate `recordBatches` and try to pass them into apache-arrow Table it fails with `Maximum call stack size exceeded` (screenshot attached)
<img width="1080" alt="image" src="https://github.com/kylebarron/arrow-js-ffi/assets/146012988/88075449-95ee-4549-a80d-ebadfea7d763">

I am not sure if I am doing something wrong getting `wasmArrowTable` from `parquet.toFFI` or that data is large (using your geo location data from `parquet-wasm` repo). 
This is combination of multiple examples that I could find that made some sense so I am sorry if I am butchering code.
And I am pretty new to parquet and arrow.

Here is all the demo code that I have needed to reproduce it. Bun is used but function `generateData` should be easily converted to what you need to reproduce it
```
import { dir } from '@stricjs/utils';
import { Router } from '@stricjs/router';
import { Table, tableFromIPC } from "apache-arrow";
import { readParquet, _memory } from "parquet-wasm/node/arrow2";
import { parseRecordBatch } from "arrow-js-ffi";

const generateData = async () => {
    const path = "./public/geo.parquet"
    const file = await Bun.file(path);
    const buff = await file.arrayBuffer()
    const bytes = new Uint8Array(buff);
    console.log(bytes.length);
    const prq = readParquet(bytes)
    const wasmArrowTable = prq.toFFI();
    console.log("numBatches", wasmArrowTable.numBatches())

    const recordBatches = [];
for (let i = 0; i < wasmArrowTable.numBatches(); i++) {
  const recordBatch = parseRecordBatch(
    _memory().buffer,
    wasmArrowTable.arrayAddr(i),
    wasmArrowTable.schemaAddr(),
    true
  );
  recordBatches.push(recordBatch);
}

console.log(recordBatches[0])
const table = new Table(recordBatches[0]);
wasmArrowTable.drop();

}

export default new Router()
  .get('/', () => new Response('Hi'))
  .get('/test', async () => {
    await generateData()
    new Response("DONE")
  })
  .get('/make', async () => {
    await makeTable()
    new Response("DONE")
  })
  .get('/*', dir('./public'));
  ```

**Comment by kylebarron** [comment] 2023-10-15 18:01
I admit it's hard to reproduce code right now because you need to combine wasm and JS, but it's impossible to reproduce/know what's happening from just the code and the screenshot.

Additionally, I haven't used Bun and it's hard to say whether that's the layer that's failing. When I've used similar code (and the test suite) in Node, I haven't gotten a recursion error

**Comment by vildantursicsymphony** [comment] 2023-10-15 18:12
Thanx for the response.
It could be very well Bun here that is causing issue, it is still fresh on the market.
I'll write here if I figure it out.
I'll try with nodejs itself to see if it will work.
Can you just confirm that steps (in this code that I pasted) for reading .parquet are fine?

**Comment by kylebarron** [comment] 2023-10-15 18:37
At a glance the code looks fine

**Comment by kylebarron** [comment] 2024-01-11 21:54
I'll close this, but feel free to reopen if you have a more reproducible example

**Closed by kylebarron** 2024-01-11 21:54 UTC
